### ISSUE TITLE
Mentor Talebi ve Onayı Sonrası Mail Gönderimi

### ISSUE THREAD

**Issue by yusufyilmazfr** [devnotcom/devnot-mentor-back-end#17]
Bazı durumlarda Mentor ve Mentee'ye mail gönderilmesi gerekmektedir.

Bunlar:

- Mentee, Mentor'e istekte bulunduğu zaman. Burada Mentor'e XYZ kişisinden sizlere bir istek var tipinde bir mail gönderimi gerekmektedir.
- Mentor'un gelen isteği onayladığı ve destek verdiği an. Burada Mentee'ye ABC Mentor'u isteğinizi kabul etti tipinde bir mail gönderimi gerekmektedir.

İlk senaryonun gerçekleştiği yer: **DevnotMentor.Api.Services** namespace altındaki **MenteeService** sınıfındaki `ApplyToMentor` metotu.
İkinci senaryonun gerçekleştiği yer: **DevnotMentor.Api.Services** namespace altındaki **MentorService** sınıfındaki `AcceptMentee` metotu.

Buradaki mail gönderme işlemini sağlayan servis **DevnotMentor.Api.Utilities.Email**  namespace altındaki **IMailService** arayüzünü kullanmaktadır. `SendEmailAsync `metotu bu işlemi gerçekleştirmektedir. Burada mail içeriği direkt kod içerisine static de yazılabilir appsettings dosyalarından da okunulabilir. İlk amaç burada işlemler sonrası mail gönderimidir.

**Comment by bariscanyilmaz** [comment]
Merhaba, 
Mentore gönderilecek mail içeriğinde isteği onayla/reddet butonu olmalı mı, yoksa sadece bildirmesi yetrerli mi?

**Comment by yusufyilmazfr** [comment]
Merhaba, bilgilendirme şu an için yeterli. Arayüz açısından bir şeyler çıktıktan sonra direkt link koyulabilir.

**Comment by bariscanyilmaz** [comment]
Bu issue'yu bana assign eder misin? Bunu geliştirmek isterim.

**Comment by yusufyilmazfr** [comment]
Tabii ki, teşekkürler şimdiden. 🎉
