### ISSUE TITLE
.Net Core 3.1'den .Net 5'e geçiş

### ISSUE THREAD

**Issue by mumincelal** [devnotcom/devnot-mentor-back-end#23]
Proje şuan .Net Core 3.1 üzerinde koşuyor. Proje .Net 5'e yükseltilebilir. Herhangi bir engel var mı bunun önünde kullanılan paketler yada başka bir şey ile alakalı?

**Comment by berkayakcay** [comment]
#26

**Comment by yusufyilmazfr** [comment]
.NET 5'e yükseltildi. 🥳
